language: python
python: 2.7
env:
  global:
    - ARTIFACTS_S3_BUCKET=sc-banner
    - ARTIFACTS_AWS_REGION=sa-east-1
    - secure: "CRwkMQIEM2ag353HAB8+TE5RXhMxjmG0DaSwmt4tL2/b3EohdyIgW08UANCluu0Ndgc4Y/BabYsbrLGAFHRbxWJ6c5NhNMxMH0JucRfus2ic+44s1LNZgeYXFNIGERWZonTty6bMK5djH+fAZTi+SDl3BsbU8Kd8fscuMiembNE="
    - secure: "Vi1dt46onzBJQ6wUv2PsvcBuNCjoT4fmcN+WOC41A/RyGXlpgdBRScJM84b6c36TpKiV9WWNhU2JUgBGTjCz558BNBVtMk9MUUMEZSrq7Dt9Up8F0kmEjS9la4DsJZLCA0nMfb6SrgUeGu6UUF1KKpH7I9Aus+kyJT19BGrNq1U="
  matrix:
    - PLONE_VERSION=4.3
install:
  - sed -ie "s#travis-4.x.cfg#travis-$PLONE_VERSION.x.cfg#" travis.cfg
  - mkdir -p buildout-cache/downloads
  - python bootstrap.py -c travis.cfg
  - bin/buildout -c travis.cfg -N -q
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script: bin/test && bin/code-analysis
after_success:
  - bin/coverage.sh
  - pip install -q coveralls
  - coveralls
after_failure:
  - bin/buildout annotate -c travis.cfg
  - firefox -v
#  - gem install travis-artifacts -q
#  - travis-artifacts upload --path parts/test
notifications:
  irc:
    channels: irc.freenode.org#simplesconsultoria
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
      - "Change view : %{compare_url}"
      - "Build details : %{build_url}"
      - "Robot Test Report: http://sc-blog.s3-website-sa-east-1.amazonaws.com/artifacts/%{build_number}"
